ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE banners AUTO_INCREMENT = 1;
ALTER TABLE categories AUTO_INCREMENT = 1;
ALTER TABLE requests AUTO_INCREMENT = 1;

DELETE FROM roles;
DELETE FROM users;
DELETE FROM requests;
DELETE FROM banners;
DELETE FROM categories;